name: Build multiplatform

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Windows
          os: windows-latest
          distpath: ./src/dist
        - name: Linux
          os: ubuntu-20.04
          distpath: ./src/dist
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests patool ttkbootstrap==1.5.1 screeninfo packaging GPUtil psutil pyinstaller cx_Freeze
    - name: Build ${{ matrix.name }}
      run: |
        cd ./src/
        python ./compile.py 
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts-${{ matrix.name }}
        path: ${{ matrix.distpath }}